#pragma once

#define OPENDRT_VERSION_MAJOR 1
#define OPENDRT_VERSION_MINOR 2
#define OPENDRT_VERSION_BUILD 0

#define OPENDRT_VERSION_STRING "1.2.0"
#define OPENDRT_BUILD_PLATFORM "Metal"

#ifdef __APPLE__
    #define OPENDRT_PLATFORM_STRING "Metal"
#elif defined(__linux__)
    #define OPENDRT_PLATFORM_STRING "CUDA"
#else
    #define OPENDRT_PLATFORM_STRING "OpenCL"
#endif

#define OPENDRT_FULL_NAME "Open DRT " OPENDRT_PLATFORM_STRING " v" OPENDRT_VERSION_STRING